# Generated by Django 4.2 on 2023-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='grades',
        ),
        migrations.AddField(
            model_name='todoitems',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='is_Completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
