# Generated by Django 4.2 on 2023-04-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_todo_grades_todoitems_createdat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitems',
            name='Describtion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todoitems',
            name='todo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.todo'),
        ),
    ]
